name: Daily Commit Bot

on:
  schedule:
    - cron: '17 13 * * *'  # Runs at 6:47 PM IST every day
  workflow_dispatch:  # Optional: allows you to run it manually

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update commit with email 23f2005402@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" > last-run.txt
          git config user.name "GitHub Action Bot"
          git config user.email "bot@users.noreply.github.com"
          git add last-run.txt
          git commit -m "Daily update: $(date -u)"
          git push

