name: Daily Commit Bot

on:
  schedule:
    # Runs every day at 04:30 UTC (adjust if needed)
    - cron: '30 4 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update commit with email 23f2005402@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" > last-run.txt
          git config user.name "GitHub Action Bot"
          git config user.email "bot@users.noreply.github.com"
          git add last-run.txt
          git commit -m "Daily update: $(date -u)"
          git push
