name: Daily Commit Bot

on:
  schedule:
    - cron: '17 13 * * *'  # 6:47 PM IST daily
  workflow_dispatch:  # allow manual trigger too

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We will manually set credentials

      - name: Set up push permissions with GITHUB_TOKEN
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Update commit with email 23f2005402@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" > last-run.txt
          git config user.name "GitHub Action Bot"
          git config user.email "bot@users.noreply.github.com"
          git add last-run.txt
          git commit -m "Daily update: $(date -u)" || echo "Nothing to commit"
          git push
